### ISSUE TITLE
Service will not start

### ISSUE THREAD

**Issue by Heppie** [alexryd/fody-tempus-pro-logger#1]
Hello,

I have followed your readme but i have a problem getting the service to start.

I am using a raspberry pi 3 and raspbian stretch

Config

{
  "influxdb": {
    "database": "Fody",
    "host": "localhost",
    "username": "",
    "password": ""
  },

  "db": {
    "path": "/var/fody/data.db"
  }
}

Logs

Dec 01 21:37:19 Ham_Pi systemd[1]: fody-tempus-pro-logger.service: Main process exited, code=exited, status=203/EXEC
Dec 01 21:37:19 Ham_Pi systemd[1]: fody-tempus-pro-logger.service: Unit entered failed state.
Dec 01 21:37:19 Ham_Pi systemd[1]: fody-tempus-pro-logger.service: Failed with result 'exit-code'.
Dec 01 21:37:29 Ham_Pi systemd[1]: fody-tempus-pro-logger.service: Service hold-off time over, scheduling restart.

**Comment by sjo00** [comment]
hello, 

i hoped to catch some fody weather data on raspberry pi 3b+ with your software. 

$ journalctl -u fody-tempus-pro-logger

Jan 26 21:36:51 loragateway systemd[1]: Started Fody Tempus Pro logger.
Jan 26 21:36:51 loragateway systemd[1389]: fody-tempus-pro-logger.service: Failed to execute command: No such file or directory
Jan 26 21:36:51 loragateway systemd[1389]: fody-tempus-pro-logger.service: Failed at step EXEC spawning /opt/nodejs/bin/fody-tempus-pro-logger: No such file or 
Jan 26 21:36:51 loragateway systemd[1]: fody-tempus-pro-logger.service: Main process exited, code=exited, status=203/EXEC
Jan 26 21:36:51 loragateway systemd[1]: fody-tempus-pro-logger.service: Failed with result 'exit-code'.
Jan 26 21:37:01 loragateway systemd[1]: fody-tempus-pro-logger.service: Service RestartSec=10s expired, scheduling restart.
Jan 26 21:37:01 loragateway systemd[1]: fody-tempus-pro-logger.service: Scheduled restart job, restart counter is at 2.
Jan 26 21:37:01 loragateway systemd[1]: Stopped Fody Tempus Pro logger.


The directory /opt/nodejs/bin/fody-tempus-pro-logger doesn't exist.

**Comment by sjo00** [comment]
The directory /opt/nodejs/bin/fody-tempus-pro-logger is configured in /etc/systemd/system/fody-tempus-pro-logger.service

I located the file /usr/local/bin/fody-tempus-pro-logger as symlink to /usr/local/lib/node_modules/fody-tempus-pro-logger also as symlink to the directory where npm install -g was started. 

But now:

Jan 26 22:06:47 loragateway systemd[1]: Started Fody Tempus Pro logger.
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]: internal/modules/cjs/loader.js:583
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     throw err;
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     ^
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]: Error: Cannot find module '/home/ttn/iot/fody-tempus-pro-logger/node_modules/sqlite3/lib/binding/node-v64-linux-arm/node_sqlite3.node'
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Module.require (internal/modules/cjs/loader.js:637:17)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at require (internal/modules/cjs/helpers.js:22:18)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Object.<anonymous> (/home/ttn/iot/fody-tempus-pro-logger/node_modules/sqlite3/lib/sqlite3.js:4:15)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Module._compile (internal/modules/cjs/loader.js:689:30)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Module.load (internal/modules/cjs/loader.js:599:32)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
Jan 26 22:06:50 loragateway fody-tempus-pro-logger[2931]:     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
Jan 26 22:06:50 loragateway systemd[1]: fody-tempus-pro-logger.service: Main process exited, code=exited, status=1/FAILURE
Jan 26 22:06:50 loragateway systemd[1]: fody-tempus-pro-logger.service: Failed with result 'exit-code'.
Jan 26 22:07:00 loragateway systemd[1]: fody-tempus-pro-logger.service: Service RestartSec=10s expired, scheduling restart.
Jan 26 22:07:00 loragateway systemd[1]: fody-tempus-pro-logger.service: Scheduled restart job, restart counter is at 5.
Jan 26 22:07:00 loragateway systemd[1]: Stopped Fody Tempus Pro logger.


Some help?
